= dap's Twitter "favorites" tool

This is a janky tool that accesses the Twitter API to download my favorite
tweets to a CSV file.  It runs in Docker to minimize how much you need to trust
any of the software.

== Initial setup

=== Twitter setup

To make any of this work, you need to:

- register as a Twitter Developer
- register a new Twitter application for this to run with.  The application will
  need read-only access to your account.

To do this, see https://github.com/sferik/t#configuration[the instructions for
the T tool, which is used under the hood here].

=== Build and run this tool

Build this image and give it a tag.  From the cloned repo as your working
directory:

[source,text]
----
$ docker build . --tag dap-twitter-favorites
----

Now, run the image.  You need to provide `TWITTER_CONSUMER_KEY` and
`TWITTER_CONSUMER_SECRET` as environment variables.  These come from the "Keys
and tokens" section of your Twitter app settings (e.g.,
`https://developer.twitter.com/en/apps/123`).

[source,text]
----
$ docker run -it \
    -e TWITTER_CONSUMER_KEY=... \
    -e TWITTER_CONSUMER_SECRET=... \
    dap-twitter-favorites
----

Make sure to use the `-it` flags, since the interactive auth process won't work
without being able to read input from your tty.

This process will:

* prompt you to authorize the app by copying a link and pasting it in your
  browser, logging into Twitter, granting the app access, and copying the PIN
  from the browser back to the terminal.
* query the Twitter API for your favorite tweets
* spit out the tweets in CSV format

=== Bugs / limitations

The program only fetches up to 10,000 tweets.  This is easy to change in
`favorites.sh`.

The app re-authorizes itself every time it runs.  I didn't want to have to store
secrets in this repo or in this image, and I only expect to run this program
occasionally, so I'm just as happy to have the creds be transient.

The CSV is spit out to stdout, which isn't super convenient because you can't
redirect it to a file without also redirecting the interactive Twitter auth
process.

== Notes

Based on https://github.com/toby/favsav[favsav].
